dist: trusty
sudo: false

matrix:
  include:
    - language: node_js
      node_js:
      - "10.14.0"
    - language: go
      go:
      - master

env:
  HUGO=0.50
  URL=https://github.com/gohugoio/hugo/releases/download

install:
  - go get github.com/gohugoio/hugo
  - hugo version
