dist: trusty
sudo: false
language: nodejs
nodejs:
  - "node"

addons:
  apt:
    packages:
      - libstdc++6
      - gcc-4.8

env:
  HUGO=0.50
  URL=https://github.com/gohugoio/hugo/releases/download

script:
  - curl -L "${URL}/v${HUGO}/hugo_extended_${HUGO}_Linux-64bit.tar.gz" | gunzip | tar xvf -
  - ls -alFh
  - ./hugo version
