dist: trusty
sudo: false

language: go
go:
  - "1.11.2"

env:
  global:
  - HUGO_BUILD_TAGS="extended"

install:
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go get github.com/magefile/mage

script:
  - go mod download
  - mage -v hugo
  - ./hugo version
