dist: trusty
sudo: false
language: node_js

env:
  HUGO=0.50
  URL=https://github.com/gohugoio/hugo/releases/download

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libstdc++6

script:
  - curl -L "${URL}/v${HUGO}/hugo_extended_${HUGO}_Linux-64bit.tar.gz" | tar xzvf -
  - ls -alFh
  - ./hugo version
