dist: trusty
sudo: false
language: node_js

env:
  HUGO=0.50
  URL=https://github.com/gohugoio/hugo/releases/download
  CXX="g++-4.8"
  CC="gcc-4.8"

addons:
  apt:
    packages:
      - libstdc++6
      - gcc-4.8

script:
  - curl -L "${URL}/v${HUGO}/hugo_extended_${HUGO}_Linux-64bit.tar.gz" | tar xzvf -
  - ls -alFh
  - ./hugo version
