dist: trusty
sudo: false

language: go
go:
  - "1.11"

env:
  global:
  - HUGO_BUILD_TAGS="extended"

install:
  # Install Hugo
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  # Checkout Hugo release v0.52
  - git checkout 9433cf5
  - go get github.com/magefile/mage
  - go mod download
  - mage -v hugo
  - ./hugo version
  - pwd
  
script:
  - $HOME/src/hugo/hugo version
  - echo "Deploy your site here"
