dist: trusty
sudo: false
language: node_js

env:
  HUGO=0.50
  URL=https://github.com/gohugoio/hugo/releases/download

before_install:
  - wget https://repo.continuum.io/archive/Anaconda2-5.3.1-Linux-x86.sh -O ~/anaconda.sh
  - bash ~/anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - conda install -y libgcc

script:
  - curl -L "${URL}/v${HUGO}/hugo_extended_${HUGO}_Linux-64bit.tar.gz" | tar xzvf -
  - ls -alFh
  - ./hugo version
